### ISSUE TITLE
Question: What target platforms are currently supported by Tightlock?

### ISSUE THREAD

**Issue by gonzaatcroud** [google-marketing-solutions/Tightlock#103]
I am scoping Tightlock to be a solution that we might be interested in implementing, but I have only found support for GA4's MP right now. Is there any other platform that the project is currently supporting or plans on supporting in the near future?

**Comment by caiotomazelli** [comment]
Hi Gonzalo, sorry for the late reply. We are working on new targets (we call them "Destinations") and you can see the ones that are currently scoped by looking at the issues marked as [Destination](https://github.com/google-marketing-solutions/Tightlock/issues?q=is%3Aopen+is%3Aissue+label%3ADestination).

**Comment by gonzaatcroud** [comment]
> Hi Gonzalo, sorry for the late reply. We are working on new targets (we call them "Destinations") and you can see the ones that are currently scoped by looking at the issues marked as [Destination](https://github.com/google-marketing-solutions/Tightlock/issues?q=is%3Aopen+is%3Aissue+label%3ADestination).

Thanks! I'll take a look!
