### ISSUE TITLE
How to make google ads conversion ?

### ISSUE THREAD

**Issue by SamuelClickage** [google-marketing-solutions/Tightlock#161]
Hello,

I need to know how to make a connection from BigQuery to Google Ads to perform a conversion.

How can I do it?

![image](https://github.com/google-marketing-solutions/Tightlock/assets/160492563/27f936ac-dc4d-405e-8d21-d5b588f44345)

**Comment by caiotomazelli** [comment]
Hi, please refer to our wiki for guidance: https://github.com/google-marketing-solutions/Tightlock/wiki/1.-Destination-Specification
