### ISSUE TITLE
Terraform Installer not working

### ISSUE THREAD

**Issue by hamza-digitl** [google-marketing-solutions/Tightlock#94]
I wanted to set up Tightlock API using Terraform installer. here is the variables.tfvars specified in this example:
```
api_key               = "9b15d73295bd24596801b544e7b7f2961ef0aafa27d5318817b4e0a918e2ab40"
project_id            = "name-of-my-project"
create_bq_sample_data = true
compute_engine_zone    = "europe-west3-a"
compute_address_region = "europe-west3"
```
The terraform apply has been successful and yielded the Connection_Code.
The problem is when trying to create the workspace using the same connection code. I get this message : 
![image](https://github.com/google/Tightlock/assets/126671212/c66580a1-5004-4df5-b944-dc455adabaaf)

All the tabs (connections, data sources,etc.) doesn't display anything.
I also tried to run the following command to interact with the api:
```
curl -i --request POST \
    --url http://$TIGHTLOCK_IP/api/v1/connect \
    --header 'X-API-KEY: '$TIGHTLOCK_API_KEY
   
```
I get the message:
```
Failed to connect : Connection timed out
``` 
Do you have any idea how to solve this problem.

**Comment by HalleyInteractive** [comment]
Hi there,

Could you double check that your Compute Engine instance can receive http traffic?
During the deployment we apply the `http-server` tag, which sometimes doesn't properly set the Firewall rule for the VM instance.

In that case most likely it says `HTTP traffic`: `Off` in the compute engine settings:
![Screenshot 2023-06-30 at 08 26 27](https://github.com/google/Tightlock/assets/1772740/974c8e03-ceff-46bd-b1ac-8bab57fd351f)

If you click on Edit in the compute engine settings and deselect `Allow HTTP traffic` and click `SAVE`.

After that select `Allow HTTP traffic` again and click `SAVE` again. 

![Screenshot 2023-06-30 at 08 28 53](https://github.com/google/Tightlock/assets/1772740/70e6f63d-3403-4116-b69f-76ba728569f7)

**Comment by hamza-digitl** [comment]
Hi,
Thank you for your response.
HTTP Traffic is allowed. I also allowed HTTPS traffic but this change did not resolve the issue.

**Comment by hamza-digitl** [comment]
I think that adding the tag `https-server` will not solve the problem as I can always see that the HTTP traffic is still set to off in the Firewalls section:
![image](https://github.com/google/Tightlock/assets/126671212/beee728a-77e1-44c9-9408-34a94498ea96)

**Comment by HalleyInteractive** [comment]
Indeed, you need the `http-server` tag, not the `https-server` tag.
Can you try to untick `Allow HTTP traffic` and then save, go back to editing and tick `Allow HTTP traffic` and save again.

From the Firewalls overview screenshot it seems that the `http-server` tag doesn't seem to trigger the actual firewall rule being added.

**Comment by hamza-digitl** [comment]
It solves the issue. It looks like ticking the `Allow HTTP traffic` and saving it again did the trick. 
Thank you very much for your support.

**Comment by HalleyInteractive** [comment]
Great to hear :D

@caiotomazelli Perhaps we should think about specifically setting the firewall rule in Terraform instead of relying on the tag?

**Comment by caiotomazelli** [comment]
> Great to hear :D
> 
> @caiotomazelli Perhaps we should think about specifically setting the firewall rule in Terraform instead of relying on the tag?

Thanks @hamza-digitl for reporting the issue and @HalleyInteractive for jumping in and helping!

The tag should work, but we can investigate if a custom rule can solve this issue. I'll investigate and report back.
